# Generated by Django 5.1.5 on 2025-01-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('year_purchased', models.IntegerField(blank=True, null=True)),
                ('year_alloted', models.IntegerField(blank=True, null=True)),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('location_of_deployment', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tracker_status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=15)),
                ('serviceability', models.CharField(choices=[('Serviceable', 'Serviceable'), ('Not Serviceable', 'Not Serviceable')], default='Serviceable', max_length=20)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnaul_date', models.DateField(blank=True, null=True)),
                ('next_overnaul_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Basic', 'Basic'), ('Overhaul', 'Overhaul')], default='Basic', max_length=15)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('scheduled', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_service_record', to='app.vehicle')),
            ],
        ),
    ]
