# Generated by Django 5.1.5 on 2025-02-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_position_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='next_overnaul_date',
            new_name='next_overhaul_date',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='overnaul_date',
            new_name='overhaul_date',
        ),
    ]
